export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const CHECKOUT_PRODUCTS_SUCCESS = 'CHECKOUT_PRODUCTS_SUCCESS';

export const CLEAR_PRODUCTS_SUCCESS = 'CLEAR_PRODUCTS_SUCCESS';

export const CHANGE_ITEM_SUCCESS = 'CHANGE_ITEM_SUCCESS';